import type { Metadata } from "next";
import { Geist, Geist_Mono,Inclusive_Sans } from "next/font/google";
import { Toaster } from "sonner";
import { AuthProvider } from "@/contexts/AuthContext";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import TopLoader from "@/components/core-components/top-loader";
import BottomNavigationFooter from "@/components/core-components/bottom-navigation-footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
 const inclusiveSans = Inclusive_Sans({
  weight: ["400"],
  display: "swap",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`antialiased ${inclusiveSans.className} `}
        suppressHydrationWarning={false}
        cz-shortcut-listen="true"
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <TopLoader />
          <AuthProvider>
            <Toaster position="top-right" />
            {children}
            <BottomNavigationFooter />
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
